//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackG {
            get {
                object obj = ResourceManager.GetObject("BackG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackG_tran {
            get {
                object obj = ResourceManager.GetObject("BackG_tran", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAbout_normal {
            get {
                object obj = ResourceManager.GetObject("btnAbout_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAbout_pressed {
            get {
                object obj = ResourceManager.GetObject("btnAbout_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnActivation_norm {
            get {
                object obj = ResourceManager.GetObject("btnActivation_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnActivation_over {
            get {
                object obj = ResourceManager.GetObject("btnActivation_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnActivation_pressed {
            get {
                object obj = ResourceManager.GetObject("btnActivation_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAdd_exceptions_norm {
            get {
                object obj = ResourceManager.GetObject("btnAdd_exceptions_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAdd_exceptions_over {
            get {
                object obj = ResourceManager.GetObject("btnAdd_exceptions_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAdd_exceptions_pressed {
            get {
                object obj = ResourceManager.GetObject("btnAdd_exceptions_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnApply_norm {
            get {
                object obj = ResourceManager.GetObject("btnApply_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnApply_over {
            get {
                object obj = ResourceManager.GetObject("btnApply_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnApply_pressed {
            get {
                object obj = ResourceManager.GetObject("btnApply_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnBrowse_disabl {
            get {
                object obj = ResourceManager.GetObject("btnBrowse_disabl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnBrowse_exceptions_norm {
            get {
                object obj = ResourceManager.GetObject("btnBrowse_exceptions_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnBrowse_exceptions_over {
            get {
                object obj = ResourceManager.GetObject("btnBrowse_exceptions_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnBrowse_exceptions_pressed {
            get {
                object obj = ResourceManager.GetObject("btnBrowse_exceptions_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnBrowse_norm {
            get {
                object obj = ResourceManager.GetObject("btnBrowse_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnBrowse_over {
            get {
                object obj = ResourceManager.GetObject("btnBrowse_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnBrowse_pressed {
            get {
                object obj = ResourceManager.GetObject("btnBrowse_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnClose_norm {
            get {
                object obj = ResourceManager.GetObject("btnClose_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnClose_over {
            get {
                object obj = ResourceManager.GetObject("btnClose_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnClose_pressed {
            get {
                object obj = ResourceManager.GetObject("btnClose_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDiagnostic_norm {
            get {
                object obj = ResourceManager.GetObject("btnDiagnostic_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDiagnostic_over {
            get {
                object obj = ResourceManager.GetObject("btnDiagnostic_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDiagnostic_pressed {
            get {
                object obj = ResourceManager.GetObject("btnDiagnostic_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDTest_norm {
            get {
                object obj = ResourceManager.GetObject("btnDTest_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDTest_over {
            get {
                object obj = ResourceManager.GetObject("btnDTest_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDTest_pressed {
            get {
                object obj = ResourceManager.GetObject("btnDTest_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnException_normal {
            get {
                object obj = ResourceManager.GetObject("btnException_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnException_pressed {
            get {
                object obj = ResourceManager.GetObject("btnException_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnHelp_norm {
            get {
                object obj = ResourceManager.GetObject("btnHelp_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnHelp_normal {
            get {
                object obj = ResourceManager.GetObject("btnHelp_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnHelp_over {
            get {
                object obj = ResourceManager.GetObject("btnHelp_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnHelp_pressed {
            get {
                object obj = ResourceManager.GetObject("btnHelp_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnHelp_pressed1 {
            get {
                object obj = ResourceManager.GetObject("btnHelp_pressed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnInGame_normal {
            get {
                object obj = ResourceManager.GetObject("btnInGame_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnInGame_pressed {
            get {
                object obj = ResourceManager.GetObject("btnInGame_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnMin_norm {
            get {
                object obj = ResourceManager.GetObject("btnMin_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnMin_over {
            get {
                object obj = ResourceManager.GetObject("btnMin_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnMin_pressed {
            get {
                object obj = ResourceManager.GetObject("btnMin_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRemove_exceptions_norm {
            get {
                object obj = ResourceManager.GetObject("btnRemove_exceptions_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRemove_exceptions_over {
            get {
                object obj = ResourceManager.GetObject("btnRemove_exceptions_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRemove_exceptions_pressed {
            get {
                object obj = ResourceManager.GetObject("btnRemove_exceptions_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRestore_norm {
            get {
                object obj = ResourceManager.GetObject("btnRestore_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRestore_over {
            get {
                object obj = ResourceManager.GetObject("btnRestore_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRestore_pressed {
            get {
                object obj = ResourceManager.GetObject("btnRestore_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSetting_normal {
            get {
                object obj = ResourceManager.GetObject("btnSetting_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSetting_pressed {
            get {
                object obj = ResourceManager.GetObject("btnSetting_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSetupScreens_norm {
            get {
                object obj = ResourceManager.GetObject("btnSetupScreens_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSetupScreens_over {
            get {
                object obj = ResourceManager.GetObject("btnSetupScreens_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSetupScreens_pressed {
            get {
                object obj = ResourceManager.GetObject("btnSetupScreens_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSimpleAdvanced_pressed {
            get {
                object obj = ResourceManager.GetObject("btnSimpleAdvanced_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnStatus_normal {
            get {
                object obj = ResourceManager.GetObject("btnStatus_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnStatus_pressed {
            get {
                object obj = ResourceManager.GetObject("btnStatus_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSTest_norm {
            get {
                object obj = ResourceManager.GetObject("btnSTest_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSTest_over {
            get {
                object obj = ResourceManager.GetObject("btnSTest_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSTest_pressed {
            get {
                object obj = ResourceManager.GetObject("btnSTest_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnTrobleshooting_norm {
            get {
                object obj = ResourceManager.GetObject("btnTrobleshooting_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnTrobleshooting_over {
            get {
                object obj = ResourceManager.GetObject("btnTrobleshooting_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnTrobleshooting_pressed {
            get {
                object obj = ResourceManager.GetObject("btnTrobleshooting_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUpdate_disabled {
            get {
                object obj = ResourceManager.GetObject("btnUpdate_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUpdate_norm {
            get {
                object obj = ResourceManager.GetObject("btnUpdate_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUpdate_normal {
            get {
                object obj = ResourceManager.GetObject("btnUpdate_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUpdate_over {
            get {
                object obj = ResourceManager.GetObject("btnUpdate_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUpdate_pressed {
            get {
                object obj = ResourceManager.GetObject("btnUpdate_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUpdate_pressed1 {
            get {
                object obj = ResourceManager.GetObject("btnUpdate_pressed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUserGuide_norm {
            get {
                object obj = ResourceManager.GetObject("btnUserGuide_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUserGuide_over {
            get {
                object obj = ResourceManager.GetObject("btnUserGuide_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnUserGuide_pressed {
            get {
                object obj = ResourceManager.GetObject("btnUserGuide_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chkbox_checked {
            get {
                object obj = ResourceManager.GetObject("chkbox_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chkbox_unchecked {
            get {
                object obj = ResourceManager.GetObject("chkbox_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diagnostic {
            get {
                object obj = ResourceManager.GetObject("Diagnostic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DriverSettings {
            get {
                object obj = ResourceManager.GetObject("DriverSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exceptionList {
            get {
                object obj = ResourceManager.GetObject("exceptionList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Exceptions {
            get {
                object obj = ResourceManager.GetObject("Exceptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_normal {
            get {
                object obj = ResourceManager.GetObject("icon_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_pressed {
            get {
                object obj = ResourceManager.GetObject("icon_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InGameSettings {
            get {
                object obj = ResourceManager.GetObject("InGameSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p1b1 {
            get {
                object obj = ResourceManager.GetObject("p1b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p1b11 {
            get {
                object obj = ResourceManager.GetObject("p1b11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p1b2 {
            get {
                object obj = ResourceManager.GetObject("p1b2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p1b3 {
            get {
                object obj = ResourceManager.GetObject("p1b3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p2b1 {
            get {
                object obj = ResourceManager.GetObject("p2b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p2b2 {
            get {
                object obj = ResourceManager.GetObject("p2b2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p2b3 {
            get {
                object obj = ResourceManager.GetObject("p2b3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p3b1 {
            get {
                object obj = ResourceManager.GetObject("p3b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p3b2 {
            get {
                object obj = ResourceManager.GetObject("p3b2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap p3b3 {
            get {
                object obj = ResourceManager.GetObject("p3b3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pageAbout {
            get {
                object obj = ResourceManager.GetObject("pageAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pageHelp {
            get {
                object obj = ResourceManager.GetObject("pageHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pageSettings {
            get {
                object obj = ResourceManager.GetObject("pageSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pageStatus {
            get {
                object obj = ResourceManager.GetObject("pageStatus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panelAutofocus {
            get {
                object obj = ResourceManager.GetObject("panelAutofocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panelBackground {
            get {
                object obj = ResourceManager.GetObject("panelBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rb_checked {
            get {
                object obj = ResourceManager.GetObject("rb_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rb_unchecked {
            get {
                object obj = ResourceManager.GetObject("rb_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SetupScreens {
            get {
                object obj = ResourceManager.GetObject("SetupScreens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatusAndMethods {
            get {
                object obj = ResourceManager.GetObject("StatusAndMethods", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tabsBackground {
            get {
                object obj = ResourceManager.GetObject("tabsBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Troubleshooting {
            get {
                object obj = ResourceManager.GetObject("Troubleshooting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Update {
            get {
                object obj = ResourceManager.GetObject("Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserGuide {
            get {
                object obj = ResourceManager.GetObject("UserGuide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
