/* IZ3D_FILE: $Id$ 
*
* Project : iZ3D Stereo Driver
* Copyright (C) iZ3D Inc. 2002 - 2009
*
* $Author$
* $Revision$
* $Date$
* $LastChangedBy$
* $URL$
*/
#include "..\BuildSetup\version.h"
#include "ProductNames.h"

#define _STR(x) #x
#define STR(x) _STR(x)
#define VERSION_NUMBER VERSION_MAJOR,VERSION_MINOR, \
								  VERSION_BUILD,PRODUCT_VERSION_QFE
#define PRODUCT_VERSION_NUMBER PRODUCT_VERSION_MAJOR,PRODUCT_VERSION_MINOR, \
								  PRODUCT_VERSION_BUILD,PRODUCT_VERSION_QFE
#define VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." \
							   STR(VERSION_BUILD) "." STR(PRODUCT_VERSION_QFE)
#define PRODUCT_VERSION_STRING VERSION

#define VERSION_COMPANY			"iZ3D Inc."
#define VERSION_COPYRIGHT		"\xA9 iZ3D Inc. All rights reserved. 2005 - 2010"
#define VERSION_TRADEMARK		""
#define VERSION_BUILD_TIME		"22:00:00GMT"
#define VERSION_BUILD_DATE_TIME RELEASE_DATA
//#define VERSION_BUILD_DATE_TIME VERSION_BUILD_DATE " - " VERSION_BUILD_TIME

#define VERSION					STR(PRODUCT_VERSION_MAJOR) "." STR(PRODUCT_VERSION_MINOR) "." \
									STR(PRODUCT_VERSION_QFE)
#define DISPLAYED_VERSION       STR(PRODUCT_VERSION_MAJOR) "." STR(PRODUCT_VERSION_MINOR) \
	VERSION_NAME_SUFFIX "(" STR(PRODUCT_VERSION_QFE) ")"
