#pragma once
#define DIRECTINPUT_VERSION 0x0800
#include <dinput.h>

template<typename Signature, Signature>
struct function_offset;

#ifndef REGISTER_FUNCTION_OFFSET
#define REGISTER_FUNCTION_OFFSET(Func, Offset) template<> struct function_offset<decltype(Func), Func> { static const int value = Offset; };
#endif

REGISTER_FUNCTION_OFFSET(&IDirectInput8A::QueryInterface, 0)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::AddRef, 1)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::Release, 2)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::CreateDevice, 3)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::EnumDevices, 4)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::GetDeviceStatus, 5)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::RunControlPanel, 6)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::Initialize, 7)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::FindDevice, 8)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::EnumDevicesBySemantics, 9)
REGISTER_FUNCTION_OFFSET(&IDirectInput8A::ConfigureDevices, 10)

REGISTER_FUNCTION_OFFSET(&IDirectInput8W::QueryInterface, 0)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::AddRef, 1)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::Release, 2)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::CreateDevice, 3)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::EnumDevices, 4)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::GetDeviceStatus, 5)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::RunControlPanel, 6)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::Initialize, 7)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::FindDevice, 8)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::EnumDevicesBySemantics, 9)
REGISTER_FUNCTION_OFFSET(&IDirectInput8W::ConfigureDevices, 10)

REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::QueryInterface, 0)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::AddRef, 1)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::Release, 2)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetCapabilities, 3)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::EnumObjects, 4)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetProperty, 5)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::SetProperty, 6)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::Acquire, 7)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::Unacquire, 8)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetDeviceState, 9)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetDeviceData, 10)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::SetDataFormat, 11)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::SetEventNotification, 12)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::SetCooperativeLevel, 13)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetObjectInfo, 14)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetDeviceInfo, 15)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::RunControlPanel, 16)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::Initialize, 17)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::CreateEffect, 18)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::EnumEffects, 19)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetEffectInfo, 20)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetForceFeedbackState, 21)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::SendForceFeedbackCommand, 22)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::EnumCreatedEffectObjects, 23)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::Escape, 24)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::Poll, 25)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::SendDeviceData, 26)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::EnumEffectsInFile, 27)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::WriteEffectToFile, 28)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::BuildActionMap, 29)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::SetActionMap, 30)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8A::GetImageInfo, 31)

REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::QueryInterface, 0)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::AddRef, 1)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::Release, 2)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetCapabilities, 3)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::EnumObjects, 4)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetProperty, 5)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::SetProperty, 6)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::Acquire, 7)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::Unacquire, 8)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetDeviceState, 9)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetDeviceData, 10)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::SetDataFormat, 11)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::SetEventNotification, 12)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::SetCooperativeLevel, 13)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetObjectInfo, 14)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetDeviceInfo, 15)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::RunControlPanel, 16)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::Initialize, 17)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::CreateEffect, 18)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::EnumEffects, 19)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetEffectInfo, 20)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetForceFeedbackState, 21)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::SendForceFeedbackCommand, 22)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::EnumCreatedEffectObjects, 23)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::Escape, 24)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::Poll, 25)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::SendDeviceData, 26)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::EnumEffectsInFile, 27)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::WriteEffectToFile, 28)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::BuildActionMap, 29)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::SetActionMap, 30)
REGISTER_FUNCTION_OFFSET(&IDirectInputDevice8W::GetImageInfo, 31)