#ifndef _IZ3DSHUTTERSERVICE_H_
#define _IZ3DSHUTTERSERVICE_H_

#if !defined _NTDDK_
	#include "winioctl.h"
#endif

#define VR_TYPE									0xc000

#define IOCTL_STARTHOOKING_SCANLINE				CTL_CODE(VR_TYPE, 0x0803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STOPHOOKING_SCANLINE				CTL_CODE(VR_TYPE, 0x0804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_INITIALIZESHUTTER					CTL_CODE(VR_TYPE, 0x0805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RELEASESHUTTER					CTL_CODE(VR_TYPE, 0x0806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STARTSHUTTER						CTL_CODE(VR_TYPE, 0x0807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STOPSHUTTER						CTL_CODE(VR_TYPE, 0x0808, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_OUTPUTDEBUGSTRING					CTL_CODE(VR_TYPE, 0x0809, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_STARTTEST							CTL_CODE(VR_TYPE, 0x0810, METHOD_BUFFERED, FILE_ANY_ACCESS)

#pragma pack (push, 1)
typedef struct _TSHUTTERINITDATA
{
	HANDLE				hEvent;
}
TSHUTTERINITDATA,*PTSHUTTERINITDATA;
#pragma pack (pop)

#endif//_IZ3DSHUTTERSERVICE_H_